---
# tasks file for webserver
- name: apt update
  apt: 
    update_cache: yes

- name: Ensure tomcat package is present
  apt:
    name: tomcat9
    state: present

- name: Ensure tomcat is started
  service:
    name: tomcat9
    state: started

- name: Synchronize webapp-file
  synchronize:
    src: /home/app/hello-1.0.war
    dest: /var/lib/tomcat9/webapps/hello-1.0.war
